# Generated by Django 6.0.3 on 2026-03-08 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_sessions', '0004_merge_20260308_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionOverallMetrics',
            fields=[
                ('session', models.OneToOneField(db_column='session_uuid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='overall_metrics_row', serialize=False, to='coach_sessions.coachingsession')),
                ('metrics', models.JSONField()),
            ],
            options={
                'db_table': 'session_overall_metrics',
            },
        ),
        migrations.CreateModel(
            name='SessionAlignedWord',
            fields=[
                ('word_id', models.IntegerField()),
                ('pk', models.CompositePrimaryKey('session', 'word_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('word_json', models.JSONField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('session', models.ForeignKey(db_column='session_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='aligned_words', to='coach_sessions.coachingsession')),
            ],
            options={
                'db_table': 'session_aligned_words',
                'indexes': [models.Index(fields=['session', 'start_time'], name='sess_align_s_start_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('event_id', models.IntegerField()),
                ('pk', models.CompositePrimaryKey('session', 'event_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('event_json', models.JSONField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('session', models.ForeignKey(db_column='session_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='coach_sessions.coachingsession')),
            ],
            options={
                'db_table': 'session_events',
                'indexes': [models.Index(fields=['session', 'start_time'], name='sess_event_s_start_idx')],
            },
        ),
    ]
